[[mgr.prepend_keymap]]
on = "l"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = "f"
run = "plugin jump-to-char"
desc = "Jump to char"

[[mgr.prepend_keymap]]
on = "<Right>"
run = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on = ["g", "g"]
run = "arrow top"
desc = "Go to top"

[[mgr.prepend_keymap]]
on = "<Home>"
run = "arrow top"
desc = "Go to top"

[[mgr.prepend_keymap]]
on = "G"
run = "arrow bot"
desc = "Go to bottom"

[[mgr.prepend_keymap]]
on = "<End>"
run = "arrow bot"
desc = "Go to bottom"

[[mgr.prepend_keymap]]
on = "n"
run = "create"
desc = "Create a new file or directory (ends with / for dirs)"

[[mgr.prepend_keymap]]
on = "a"
run = "create --dir"
desc = "Create a new directory"

[[mgr.prepend_keymap]]
on = "A"
run = "rename --cursor=start"
desc = "Rename a file or directory - start at the beginning"

[[mgr.prepend_keymap]]
on = "R"
run = "rename --empty=all"
desc = "Rename a file or directory - start with empty prompt"

[[mgr.prepend_keymap]]
on = ":"
run = "shell --interactive"
desc = "Run a shell command"

[[mgr.prepend_keymap]]
on = ";"
run = "shell --interactive --block"
desc = "Run a shell command - block the UI until the command finishes"

[[mgr.prepend_keymap]]
on = "<S-Tab>"
run = "tab_switch -1 --relative"
desc = "Switch to the previous tab"

[[mgr.prepend_keymap]]
on = "<Tab>"
run = "tab_switch 1 --relative"
desc = "Switch to the next tab"

[[mgr.prepend_keymap]]
on = ["g", "i"]
run = "cd /run/media/sveatlo/"
desc = "Go to media"

[[mgr.prepend_keymap]]
on = ["g", "m"]
run = "cd /mnt"
desc = "Go to /mnt"

[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open $SHELL here"


[[mgr.prepend_keymap]]
on = ["<C-o>"]
for = "unix"
run = 'shell "nvim +Oil" --block --confirm'
desc = "Open current directory in oil.nvim"

[[mgr.prepend_keymap]]
on = "y"
run = [
  'shell -- for path in %s; do echo "file://$path"; done | wl-copy -t text/uri-list',
  "yank",
]

[[mgr.prepend_keymap]]
on = "<C-g>"
run = 'shell -- rofi -theme fullscreen-preview -show filebrowser -filebrowser-command "ya emit reveal" -filebrowser-directory "$(pwd)"'
desc = "Grid view"

[[mgr.prepend_keymap]]
on = "<C-m>"
run = '''shell --
	paths=$(for p in %s; do echo "$p"; done | paste -s -d,)
	thunderbird -compose "attachment='$paths'"
'''
